"""admin-v2

Revision ID: 24dc6263c78d
Revises: 0d765c49fe1f
Create Date: 2026-09-25 21:22:01.249848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24dc6263c78d'
down_revision: Union[str, Sequence[str], None] = '0d765c49fe1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentation', sa.Column('owner_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'presentation', 'admin', ['owner_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'presentation', schema='public', type_='foreignkey')
    op.drop_column('presentation', 'owner_id')
    # ### end Alembic commands ###
