"""prev-img

Revision ID: 8a41b2ed659d
Revises: 18b5a798c696
Create Date: 2026-09-23 17:25:12.679296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a41b2ed659d'
down_revision: Union[str, Sequence[str], None] = '18b5a798c696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentation', sa.Column('file', sa.String(length=30), nullable=True))
    op.execute("""
        UPDATE presentation
        SET file = html_file
        WHERE file IS NULL
    """)
    op.add_column('presentation', sa.Column('preview_image', sa.String(length=40), nullable=True))
    op.drop_column('presentation', 'html_file')
    op.alter_column(
        "presentation",
        "file",
        existing_type=sa.String(length=30),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentation', sa.Column('html_file', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.execute("""
            UPDATE presentation
            SET html_file = file
            WHERE html_file IS NULL
        """)
    op.drop_column('presentation', 'preview_image')
    op.drop_column('presentation', 'file')
    op.alter_column(
        "presentation",
        "html_file",
        existing_type=sa.String(length=30),
        nullable=False,
    )
    # ### end Alembic commands ###
