"""admin_v3

Revision ID: 9b458570650f
Revises: 24dc6263c78d
Create Date: 2026-10-03 22:46:32.763198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b458570650f'
down_revision: Union[str, Sequence[str], None] = '24dc6263c78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('login', sa.String(length=256), nullable=True))
    op.add_column('admin', sa.Column('password', sa.String(), nullable=True))
    op.drop_constraint(op.f('presentation_owner_id_fkey'), 'presentation', type_='foreignkey')
    op.create_foreign_key(None, 'presentation', 'admin', ['owner_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'presentation', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('presentation_owner_id_fkey'), 'presentation', 'admin', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('admin', 'password')
    op.drop_column('admin', 'login')
    # ### end Alembic commands ###
