"""admin_v3_release

Revision ID: a7025a647cea
Revises: 9b458570650f
Create Date: 2026-10-03 22:48:44.252233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7025a647cea'
down_revision: Union[str, Sequence[str], None] = '9b458570650f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'login',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('admin', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('presentation_owner_id_fkey'), 'presentation', type_='foreignkey')
    op.create_foreign_key(None, 'presentation', 'admin', ['owner_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'presentation', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('presentation_owner_id_fkey'), 'presentation', 'admin', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('admin', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('admin', 'login',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
