"""admin_v3_release

Revision ID: c802907da0ee
Revises: a7025a647cea
Create Date: 2026-10-05 22:27:36.949270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c802907da0ee'
down_revision: Union[str, Sequence[str], None] = 'a7025a647cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'admin', ['login'], schema='public')
    op.drop_constraint(op.f('presentation_owner_id_fkey'), 'presentation', type_='foreignkey')
    op.create_foreign_key(None, 'presentation', 'admin', ['owner_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'presentation', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('presentation_owner_id_fkey'), 'presentation', 'admin', ['owner_id'], ['id'], ondelete='CASCADE')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'admin', schema='public', type_='unique')
    op.alter_column('admin', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
